# For now, new posts should be added above older ones, as the order of this file will set the order of the timeline.
# posts
'posts/art/doh-noot_smile':
  title: 'Doh-Noot - #1: Smiling'
  short: 'Just don''t let Doh-Noot walk into the donut shop, okay?'
  type: post
  og-image: /assets/img/media/art/dn/dn_smile_tr.png
  title-display: true
  date:
    posted: 1689726261
    edited: 1690758605
  filename: art/doh-noot_smile
  category: My art
  tags: 'art, donut, emoji, drawing, Clip Studio Paint, OCs, OC, OCid:DN'
'posts/art/mousemouse-3.2-textured':
  title: MouseMouse retextured
  short: The 4K mousemouse I posted earlier in a new papertextured mix!
  type: post
  og-image: /assets/img/media/art/MM2-textured.png
  title-display: true
  date:
    posted: 1689715712
    edited: 1690758605
  filename: art/mousemouse-3.2-textured
  category: My art
  tags: 'art, tumblr, mouse, mousemouse, mousemaus, Clip Studio Paint, OCs, OC, OCid:MM, paper textured'
'posts/art/brain-lost-misunderstanding':
  title: 'A misunderstanding'
  short: 'Just trying things out lol'
  type: post
  og-image: /assets/img/media/art/a-misunderstanding.png
  title-display: true
  content: |
    - More brainfarts that I turned to art: <code class="taggo">brainfart as art</code>

    <div style="height: 300px"><hl-img preview="https://64.media.tumblr.com/c8d4a3e20145e846bf96bc5ca16da14e/bc5fb4c5e676e41b-93/s1280x1920/ead37ff27590d344cf2a48dc1dd812468256e43e.pnj" alt="MouseMouse!" highlight="/assets/img/media/art/a-misunderstanding.png" href="https://www.tumblr.com/strawmelonjuice/722847916036931584/a-misunderstanding?source=share"></hl-img></div>

    A misunderstanding! Will the bunny-thing eat the mole-thing? I think they'll become friends.

    <span class="notion">This art is mine, you may not download and use this without [asking me](mailto:mar@strawmelonjuice.com) and getting my permission!</span>
  date:
    posted: 1689354605
    edited: 1690984579
  filename: art/brain-lost-misunderstanding
  category: My art
  tags: 'art, animals, emoji, drawing, Clip Studio Paint, OC, trying things out, paper textured, brainfart as art'
'posts/LDo/230704':
  title: Logger-Diary Online is coming back to Mar's home domain.
  short: Logger-Diary Online is coming back to `logger-diary.strawmelonjuice.com` for financial reasons.
  type: post
  title-display: true
  filename: LDo/230704
  category: Logger-Diary Online
  modeoverride: project
  og-image: https://logger-diary.strawmelonjuice.com/img/logo/logo_512px.png
  date:
    posted: 1688485329
    edited: 1688485329
'posts/art/mousemouse-3.2':
  title: MouseMouse in hi-res!
  short: MouseMouse redone in a 4k canvas by me!
  type: post
  og-image: /assets/img/media/art/MM2.webp
  title-display: true
  date:
    posted: 1688332202
    edited: 1690758605
  filename: art/mousemouse-3.2
  category: My art
  tags: 'art, tumblr, mouse, mousemouse, mousemaus, Clip Studio Paint, OCs, OC, OCid:MM'
'posts/ads-no-more':
  title: Going ad-less.
  short: First Google Adsense, now adfocus too. Going ad-less.
  type: post
  title-display: true
  date:
    posted: 1687804698
    edited: 1687814181
  filename: ads-no-more
  category: Meta
  tags: Google Adsense, Google, critique, adfocus, adfoc.us
'posts/art/bb_hi':
  title: "Bella bee: Hi!"
  short: A first try that went exceptionally well!
  type: post
  og-image: /assets/img/media/art/BB/Bella Bee hi marked.png
  title-display: true
  date:
    posted: 1687541312
    edited: 1690758605
  filename: art/bb_hi
  category: My art
  tags: 'art, tumblr, animals, bee, Clip Studio Paint, OCs, OC, OCid:BB'
'posts/LDo/230608':
  title: Logger-Diary News now served on Mar's website!
  short: Logger-Diary Online News is now served from `strawmelonjuice.com`.
  type: post
  title-display: true
  filename: LDo/230608
  category: Logger-Diary Online
  og-image: https://logger-diary.strawmelonjuice.com/img/logo/logo_512px.png
  modeoverride: project
  date:
    posted: 1686248156
    edited: 1686248156
'posts/kitton':
  title: Kitten!
  short: My site now has a cat following your mouse around!
  filename: kitton
  content: |
    My site now has a cat following your mouse around. 
    The kitten will only follow you on pages of the type 'base', so not on blog pages or pages that are set to be a different type.
    
    I think it's cute.

    Edit: The filters were also broken for a rlly long time! They work now without screwing up the page, and remember your setting for 30 days across pages! UwU
  type: post
  category: Meta
  date:
    posted: 1686134666
    edited: 1686139710
  tags: javascript, adryd, maia arson crimew, open-source, web, webdev
'posts/wordpress-2023-05-30':
  title: No more Wordpress
  short: This site no longer runs on Wordpress, this is how and why I did it.
  type: post
  filename: wordpress-2023-05-30
  category: Meta
  date:
    posted: 1685451731
    edited: 1685451731
  tags: blog, webdev, php, tech, CMS, GitHub, themes
'posts/LDo/moved-to-logger-diary.online':
  title: "We moved to a new adress - `https://logger-diary.online`"
  short: We moved to our own adress!
  type: post
  og-image: https://logger-diary.strawmelonjuice.com/img/logo/logo_512px.png
  title-display: false
  filename: LDo/moved-to-logger-diary.online
  category: Logger-Diary Online
  modeoverride: project
  date:
    posted: 1674730800
    edited: 1674730800
  tags: diary-app, domain name, moving
'posts/LDo/md':
  title: Markdown support!
  short: Logger-Diary Online now has markdown support!
  og-image: https://logger-diary.strawmelonjuice.com/img/logo/logo_512px.png
  type: post
  title-display: true
  filename: LDo/md
  category: Logger-Diary Online
  modeoverride: project
  date:
    posted: 1674471600
    edited: 1674730800
  tags: diary-app, markdown, daring fireball, updates, site, parsedown
'posts/farewell-gads':
  title: Farewell Google Adsense then
  short: I dropped Google Adsense after they started acting weird. How to continue?
  type: post
  title-display: true
  date:
    posted: 1661359098
    edited: 1687854166
  filename: farewell-gads
  category: Meta
  tags: Google Adsense, Google, critique
'posts/art/af-hi':
  title: "Amigo & Ferry: Hi"
  short: Two shy best friends!
  type: post
  og-image: /assets/img/media/art/AF/hi.png
  title-display: true
  date:
    posted: 1668724112
    edited: 1690758605
  filename: art/af-hi
  category: My art
  tags: 'art, discord, slug, cactus, friends, Clip Studio Paint, OCs, OC, OCid:AF'
'posts/stories/leafornia-2':
  title: Leafornia’s travels - chapter two
  short: Today went bad. I underestimated how hard it is for me to live here. Physically, I am weaker than my lost demon. However, I don’t know if this world didn’t mess him up mentally. I also need to take in consideration that my normal me is weak in this world, and that my powers are way too strong for this world. I may no longer use my powers if unnecessarily. Regards from earth.
  type: post
  title-display: true
  filename: stories/leafornia-2
  category: Story ideas:<br> Leafornia's travels
  date:
    posted: 1635885176
    edited: 1635885176
  tags: hell, devil, girl, fiction, 2021, Leafornia's travels, Story ideas
'posts/stories/leafornia-1':
  title: Leafornia’s travels - chapter one
  short: “No, I beg you! I’ll do my best next time, I’ll make sure your fire is as hot as you want it! Please!” She sat back in her red velvet throne, looking him dead in the eye, making clear that his begging made no sense to her. “You foolish giant demon. I do not see why I should spare you, for it is only one human life, and you did not quite do as you promised last time.”, she spoke. “And no. I do not care about the temperature of my fire, it is only for decoration. I’ll just send you there because that’s what I do, no reason behind it.”
  type: post
  title-display: true
  filename: stories/leafornia-1
  category: Story ideas:<br> Leafornia's travels
  date:
    posted: 1633519196
    edited: 1633519196
  tags: hell, devil, girl, fiction, 2021, satans daughter, Leafornia's travels, Story ideas
#pages
'1':
  title: About me
  title-display: false
  short: About mar
  type: page
  date:
    posted: 1683723800
    edited: 1683723800
  tags: autobiographical, quotes
'abt-site':
  title: About this site
  short: About this site
  type: page
  title-display: true
  date:
    posted: 1686090592
    edited: 1688303399
  tags: meta, credits
'links':
  title: My important links
  short: Mar's links
  morelinks-display: false
  type: page
  date:
    posted: 1683723800
    edited: 1683723800
  tags: linktree, social media, links
'discord/docs/rules':
  title: Server rules
  short: Rules for the 'BLUB!!' discord server.
  modeoverride: discord
  type: page
  date:
    posted: 1676247185
    edited: 1685887840
  tags: discord, moderator, moderation, discord server, rules
'support':
  title: Support me
  short: Like what I do? Want to support me? You'll find some links on this page!
  modeoverride: base
  type: page
  date:
    posted: 1686237433
    edited: 1686237433
  tags: donation, support, paypal, buymeacoffee, open-source
'projects':
  title: Projects
  short: I am a creativity addict so I jiggle around with code from time to time.
  modeoverride: project
  type: page
  date:
    posted: 1686237433
    edited: 1687804698
  tags: donation, support, paypal, buymeacoffee, open-source, github
'projects/hl-img':
  title: HL-img.js > Home
  short: Page (and theme) under construction!
  modeoverride: project
  type: page
  date:
    posted: 1689201880
    edited: 1689201880
  tags: donation, support, paypal, buymeacoffee, open-source, javascript
