'1':
  title: About me
  short: About mar
  type: page
  date:
    posted: 1683723800
    edited: 1683723800
  
'2':
  title: My links
  short: Mar's links
  type: page
  date:
    posted: 1683723800
    edited: 1683723800
'posts/wordpress-2023-05-30':
  title: No more Wordpress
  short: This site no longer runs on Wordpress, this is how and why I did it.
  type: post
  filename: wordpress-2023-05-30
  date:
    posted: 1685451731
    edited: 1685451731
'posts/test':
  title: No more .md files
  content: |
    ### Heading

    * Bullet
    * Points
  short: YAML stores these b*tches too now.
  type: page
  filename: wordpress-2023-05-30
  date:
    posted: 1685887840
    edited: 1685887840