# For now, new posts should be added above older ones, as the order of this file will set the order of the timeline.
# posts
'posts/kitton':
  title: Kitten!
  short: My site now has a cat following your mouse around!
  filename: kitton
  content: |
    My site now has a cat following your mouse around. 
    The kitten will only follow you on pages of the type 'base', so not on blog pages or pages that are set to be a different type.
    
    I think it's cute.

    Edit: The filters were also broken for a rlly long time! They work now without screwing up the page, and remember your setting for 30 days across pages! UwU
  type: post
  category: Meta
  date:
    posted: 1686134666
    edited: 1686139710
'posts/wordpress-2023-05-30':
  title: No more Wordpress
  short: This site no longer runs on Wordpress, this is how and why I did it.
  type: post
  filename: wordpress-2023-05-30
  category: Meta
  date:
    posted: 1685451731
    edited: 1685451731
#pages
'1':
  title: About me
  title-display: false
  short: About mar
  type: page
  date:
    posted: 1683723800
    edited: 1683723800
'meta-abt':
  title: About this site
  short: About this site
  type: page
  title-display: true
  date:
    posted: 1686090592
    edited: 1686118780
'2':
  title: My links
  short: Mar's links
  type: page
  date:
    posted: 1683723800
    edited: 1683723800
'tests/mdinyaml':
  title: No more .md files
  short: YAML stores these b*tches too now.
  content: |
    ### Heading

    * Bullet
    * Points
  category: Meta
  type: page
  modeoverride: blog
  date:
    posted: 1685887840
    edited: 2685887840
'discord/docs/rules':
  title: Server rules
  short: Rules for the 'BLUB!!' discord server.
  modeoverride: discord
  type: page
  date:
    posted: 1676247185
    edited: 1685887840
'support':
  title: Support me
  short: Like what I do? Want to support me? You'll find some links on this page!
  modeoverride: base
  type: page
  date:
    posted: 1686237433
    edited: 1686237433