# For now, new posts should be added above older ones, as the order of this file will set the order of the timeline.
# posts
'posts/ads-no-more':
  title: Going ad-less.
  short: First Google Adsense, now adfocus too. Going ad-less.
  type: post
  title-display: true
  date:
    posted: 1687804698
    edited: 1687814181
  filename: ads-no-more
  category: Meta
  tags: Google Adsense, Google, critique, adfocus, adfoc.us
'posts/LDo/230608':
  title: Logger-Diary News now served on Mar's website!
  short: Logger-Diary Online News is now served from `strawmelonjuice.com`.
  type: post
  title-display: true
  filename: LDo/230608
  category: Logger-Diary Online
  modeoverride: base
  date:
    posted: 1686248156
    edited: 1686248156
'posts/kitton':
  title: Kitten!
  short: My site now has a cat following your mouse around!
  filename: kitton
  content: |
    My site now has a cat following your mouse around. 
    The kitten will only follow you on pages of the type 'base', so not on blog pages or pages that are set to be a different type.
    
    I think it's cute.

    Edit: The filters were also broken for a rlly long time! They work now without screwing up the page, and remember your setting for 30 days across pages! UwU
  type: post
  category: Meta
  date:
    posted: 1686134666
    edited: 1686139710
  tags: javascript, adryd, maia arson crimew, open-source, web, webdev
'posts/wordpress-2023-05-30':
  title: No more Wordpress
  short: This site no longer runs on Wordpress, this is how and why I did it.
  type: post
  filename: wordpress-2023-05-30
  category: Meta
  date:
    posted: 1685451731
    edited: 1685451731
  tags: blog, webdev, php, tech, CMS, GitHub, themes
'posts/LDo/moved-to-logger-diary.strawmelonjuice.com':
  title: "We moved to a new adress - `https://logger-diary.strawmelonjuice.com`"
  short: We moved to our own adress!
  type: post
  title-display: false
  filename: LDo/moved-to-logger-diary.strawmelonjuice.com
  category: Logger-Diary Online
  modeoverride: base
  date:
    posted: 1674730800
    edited: 1674730800
  tags: diary-app, domain name, moving
'posts/LDo/md':
  title: Markdown support!
  short: Logger-Diary Online now has markdown support!
  type: post
  title-display: true
  filename: LDo/md
  category: Logger-Diary Online
  modeoverride: base
  date:
    posted: 1674471600
    edited: 1674730800
  tags: diary-app, markdown, daring fireball, updates, site, parsedown
'posts/farewell-gads':
  title: Farewell Google Adsense then
  short: I dropped Google Adsense after they started acting weird. How to continue?
  type: post
  title-display: true
  date:
    posted: 1661359098
    edited: 1687854166
  filename: farewell-gads
  category: Meta
  tags: Google Adsense, Google, critique
'posts/stories/leafornia-2':
  title: Leafornia’s travels - chapter two
  short: Today went bad. I underestimated how hard it is for me to live here. Physically, I am weaker than my lost demon. However, I don’t know if this world didn’t mess him up mentally. I also need to take in consideration that my normal me is weak in this world, and that my powers are way too strong for this world. I may no longer use my powers if unnecessarily. Regards from earth.
  type: post
  title-display: true
  filename: stories/leafornia-2
  category: Story ideas:<br> Leafornia's travels
  date:
    posted: 1635885176
    edited: 1635885176
  tags: hell, devil, girl, fiction, 2021
'posts/stories/leafornia-1':
  title: Leafornia’s travels - chapter one
  short: “No, I beg you! I’ll do my best next time, I’ll make sure your fire is as hot as you want it! Please!” She sat back in her red velvet throne, looking him dead in the eye, making clear that his begging made no sense to her. “You foolish giant demon. I do not see why I should spare you, for it is only one human life, and you did not quite do as you promised last time.”, she spoke. “And no. I do not care about the temperature of my fire, it is only for decoration. I’ll just send you there because that’s what I do, no reason behind it.”
  type: post
  title-display: true
  filename: stories/leafornia-1
  category: Story ideas:<br> Leafornia's travels
  date:
    posted: 1633519196
    edited: 1633519196
  tags: hell, devil, girl, fiction, 2021, satans daughter
#pages
'1':
  title: About me
  title-display: false
  short: About mar
  type: page
  date:
    posted: 1683723800
    edited: 1683723800
  tags: autobiographical, quotes
'meta-abt':
  title: About this site
  short: About this site
  type: page
  title-display: true
  date:
    posted: 1686090592
    edited: 1686118780
  tags: meta, credits
'2':
  title: My links
  short: Mar's links
  type: page
  date:
    posted: 1683723800
    edited: 1683723800
  tags: linktree, social media, links
'discord/docs/rules':
  title: Server rules
  short: Rules for the 'BLUB!!' discord server.
  modeoverride: discord
  type: page
  date:
    posted: 1676247185
    edited: 1685887840
  tags: discord, moderator, moderation, discord server, rules
'support':
  title: Support me
  short: Like what I do? Want to support me? You'll find some links on this page!
  modeoverride: base
  type: page
  date:
    posted: 1686237433
    edited: 1686237433
  tags: donation, support, paypal, buymeacoffee, open-source
'projects':
  title: Projects
  short: I am a creativity addict so I jiggle around with code from time to time.
  modeoverride: base
  type: page
  date:
    posted: 1686237433
    edited: 1687804698
  tags: donation, support, paypal, buymeacoffee, open-source, github